name: update-deploy-status
description: Log the deploy status to DynamoDB
inputs:
  status:
    description: 'Status to log'
    required: true
    default: 'unknown'

runs:
  using: "Composite"
  steps:
    - name: Prepare data
      id: prepare-data
      run: |
        echo "$(git branch)"
        echo "deployed-branch=$(git show ${{ github.sha }}^2 --pretty="format:%D" -s)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Put DynamoDB Item
      uses: mooyoul/dynamodb-actions@v1.2.1
      env:
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_REGION: ap-northeast-1
      with:
        operation: put
        region: ap-northeast-1
        table: deploy-tool-environment-status
        item: |
          {
            environment: "${{ github.ref_name }}",
            module: "dw-nfc-server",
            branch: "${{ steps.prepare-data.output.deployed-branch }}",
            status: "${{ inputs.status }}"
          }
