name: Rebase pre-dev branches

on:
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [pre-dev1, pre-dev2]
    permissions:
      contents: write
    continue-on-error: true
    outputs:
      overall: ${{ steps.job-output.outputs.OVERALL }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout target branch
        run: |
          git checkout ${{ matrix.branch }}

      - name: Rebase onto main
        run: |
          git rebase origin/main

      - name: Push updated branch
        run: |
          git push origin ${{ matrix.branch }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle result
        if: failure()
        id: job-output
        run: |
          echo "OVERALL=failure" >> $GITHUB_OUTPUT
          exit 1
  
  check-failures:
    runs-on: ubuntu-latest
    needs: rebase
    if: needs.rebase.outputs.overall == 'failure'
    steps:
      - name: Failure exiting
        run: exit 1