name: Rebase pre-dev branches

on:
  workflow_dispatch:
    inputs:
      exclude:
        type: string
        required: false
        description: "Branches which should not be backported. Ex: pre-dev-dx1 pre-dev-mm1"
      include:
        type: string
        required: false
        description: "Branches which should also be backported too. Ex: pre-dev-dx1-edited pre-dev-mm1-custom"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.generate-matrix.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate matrix
        id: generate-matrix
        env:
          input_exclude_branches: ${{ inputs.exclude }}
          input_include_branches: ${{ inputs.include }}
        run: |
          git fetch --all
          default_branches=$(git branch -r | sed 's/origin\///' | awk '{$1=$1};1' | grep '^pre-dev' | jq -R . | jq -s .)
          exclude_branches=$(echo "$input_exclude_branches" | jq -R 'split(" ")')
          include_branches=$(echo "$input_include_branches" | jq -R 'split(" ")')
          target_branches=$(echo "$default_branches" | jq --argjson remove_list "$exclude_branches" --argjson add_list "$include_branches" '
            . as $array |
            ($array | map(select(. as $item | $remove_list | index($item) | not))) + $add_list
          ' | jq -r @json)
          echo $default_branches
          echo $target_branches
          echo "branches=$target_branches" >> $GITHUB_OUTPUT

  rebase:
    name: Rebase branch
    needs: init
    uses: ./.github/workflows/rebase_and_build.yaml
    with:
      predev: ${{ matrix.branch }}
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.init.outputs.branches) }}
