name: Rebase pre-dev branches

on:
  workflow_dispatch:
    inputs:
      exclude:
        type: string
        required: false
        description: Exclude branches. Input multiple with comma separation.

jobs:
  rebase:
    name: Rebase all predev branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [pre-dev1, pre-dev2, pre-dev3]
    permissions:
      contents: write
    continue-on-error: true
    outputs:
      overall: ${{ steps.job-output.outputs.OVERALL }}
    steps:
      - name: Check executable
        run: |
          INPUT_LIST="${{ inputs.exclude }}"
          IFS=',' read -ra VALUES <<< "$INPUT_LIST"
          for value in "${VALUES[@]}"; do
            if [[ "$value" == "${{ matrix.branch }}" ]]; then
              exit 0
            fi
          done
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout target branch
        run: |
          git checkout ${{ matrix.branch }}

      - name: Rebase onto main
        run: |
          git rebase origin/main

      - name: Push updated branch
        run: |
          git push origin ${{ matrix.branch }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle result
        if: failure()
        id: job-output
        run: |
          echo "OVERALL=failure" >> $GITHUB_OUTPUT
          exit 1
  
  exit-with-failures:
    name: Exit with failure
    runs-on: ubuntu-latest
    needs: rebase
    if: needs.rebase.outputs.overall == 'failure'
    steps:
      - name: Failure exiting
        run: exit 1