name: Rebase pre-dev branches

on:
  workflow_dispatch:

env:
  OVERALL: success

jobs:
  rebase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [pre-dev1, pre-dev2]
    permissions:
      contents: write
    continue-on-error: true
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout target branch
        run: |
          git checkout ${{ matrix.branch }}

      - name: Rebase onto main
        run: |
          git rebase origin/main

      - name: Push updated branch
        run: |
          git push origin ${{ matrix.branch }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle rebase conflicts
        if: failure()
        run: |
          echo "OVERALL=failure" >> $GITHUB_ENV
          exit 1
  
  check-failures:
    runs-on: ubuntu-latest
    needs: rebase
    steps:
      - name: Conditional exiting
        run: '[ "$OVERALL" = "failure" ] && exit 1'