name: Build and push to each environments based on a tag
on:
  workflow_call:
    inputs:
      version:
        description: "Version to tag to docker image"
        type: string
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      ref: ${{ inputs.version }}
