name: Build lsm image
on:
  workflow_call:
    inputs:
      ref:
        description: "Which application version"
        required: false
        type: string
        default: main

env:
  APP_REPO: test-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.APP_REPO }}
          ref: ${{ inputs.ref }}
          submodules: recursive
          ssh-key: ${{ secrets.APP_DEPLOY_KEY }}

      - name: Prepare docker image tag
        env:
          INPUT_REF: ${{ inputs.ref }}
        run: |
          if [ $INPUT_REF == 'main' ]; then
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ inputs.ref }}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . # See: https://github.com/docker/build-push-action/issues/300
          tags: ${{ env.IMAGE_TAG }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
