name: Trigger deploy production
on:
  push:
    branches:
      - production
    paths:
      - "version.txt"

jobs:
  validate:
    name: Validate version
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.manifest.outputs.MANIFEST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Valid version
        run: |
          set -e
          target_ver=$(cat version.txt)
          tag_hash=$(git rev-parse $target_ver)
          last_commit_hash=$(git log -1 --pretty=%P)
          if [ "$last_commit_hash" = "$tag_hash" ]; then
            echo "Branch is valid and process deployment"
          else
            echo "This branch was not created correctly. Please recreate from right tag and try again."
            exit 1
          fi

      - name: Update release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          target_ver=$(cat version.txt)
          gh release edit $target_ver --latest

  deploy-default:
    needs: validate
    uses: ./.github/workflows/s3-prod-deploy.yml
    with:
      version: ${{ github.ref_name }}
  deploy-qlover:
    needs: validate
    uses: ./.github/workflows/s3-prod-qlover-deploy.yml
    with:
      version: ${{ github.ref_name }}
  deploy-channel:
    needs: validate
    uses: ./.github/workflows/s3-prod-channel-deploy.yml
    with:
      version: ${{ github.ref_name }}
