name: Cherry pick features to release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch which prs will be merge into."
        required: true
        type: string
      prs:
        description: "PRs to cherry pick. Seperate by comma."
        required: true
        type: string

jobs:
  validate:
    name: cherry pick features
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update release
        env:
          UPSTREAM_REMOTE: origin
          GITHUB_USER: ${{ github.repository_owner }}
          MAIN_REPO_ORG: ${{ github.repository_owner }}
          MAIN_REPO_NAME: ${{ github.event.repository.name }}
        run: ./.github/scripts/cherry_pick_pull.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.prs }}
