name: Cherry pick features to release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch which prs will be merge into."
        required: true
        type: string
      pr:
        description: "PR to cherry pick."
        required: true
        type: string
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  validate:
    name: cherry pick features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          source_pr_number: ${{ github.event.inputs.pr }}
          target_branches: ${{ github.event.inputs.branch }}
