name: Deploy pre-dev
on:
  push:
    branches:
      - pre-dev*
  workflow_call:
    inputs:
      predev:
        description: "Predev name"
        type: string
        required: true
     
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
