name: Trigger deploy staging
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy to staging"
        required: true
        type: string

jobs:
  validate:
    name: Validate version
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
      - name: Update release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ inputs.version }} --draft=false --prerelease=true

  deploy-sheeta:
    needs: validate
    uses: ./.github/workflows/s3-staging-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-qlover:
    needs: validate
    uses: ./.github/workflows/s3-staging-qlover-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-channel:
    needs: validate
    uses: ./.github/workflows/s3-staging-channel-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-ado:
    needs: validate
    uses: ./.github/workflows/s3-staging-ado-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-hamabe:
    needs: validate
    uses: ./.github/workflows/s3-staging-hamabeminami-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-hololive:
    needs: validate
    uses: ./.github/workflows/s3-staging-hololive-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-horizon:
    needs: validate
    uses: ./.github/workflows/s3-staging-horizon-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-matsumaru:
    needs: validate
    uses: ./.github/workflows/s3-staging-matsumaru-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-takahashi:
    needs: validate
    uses: ./.github/workflows/s3-staging-takahashi-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-tokinosora:
    needs: validate
    uses: ./.github/workflows/s3-staging-tokinosora-deploy.yml
    with:
      version: ${{ inputs.version }}
  deploy-tym:
    needs: release
    uses: ./.github/workflows/s3-staging-tym-deploy.yml
    with:
      version: ${{ inputs.version }}
