name: release hotfix
on:
  push:
    branches:
      - v[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

jobs:
  init-version:
    if: github.event.push.created == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tag
        run: |
          git tag ${{github.ref_name}}.0
          git push origin ${{github.ref_name}}.0
  tag-version:
    if: github.event.push.created == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: paulhatch/semantic-version@v5.4.0
        with:
          version_from_branch: "/v([0-9]+.[0-9]+$|[0-9]+)$/"
