name: release hotfix
on:
  push:
    branches:
      - v[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

jobs:
  init-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          version_format: "${major}"
          bump_each_commit: true
          version_from_branch: "/v[0-9]+$/"
      - name: tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ${{ steps.version.outputs.version_type }}
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
          gh release create --generate-notes --notes-start-tag ${{ steps.version.outputs.previous_version }} ${{ steps.version.outputs.version }}
