name: Version release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate release notes
        run: |
          $previous_latest=$(gh release list --jq '.[] | select(.isLatest == true)' --json name,isLatest | jq -r '.name')
            gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
            /${{ github.repository }}/releases/generate-notes -f "tag_name=v20240802.9" -f "target_commitish=main" -f "previous_tag_name=$previous_latest"
          echo "PREV_TAG=$previous_latest" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{ env.PREV_TAG }}
  deploy-default:
    needs: release
    uses: ./.github/workflows/s3-mlstg-deploy.yml
    with:
      version: ${{ github.ref_name }}
  deploy-qlover:
    needs: release
    uses: ./.github/workflows/s3-mlstg-qlover-deploy.yml
    with:
      version: ${{ github.ref_name }}
  deploy-channel:
    needs: release
    uses: ./.github/workflows/s3-mlstg-channel-deploy.yml
    with:
      version: ${{ github.ref_name }}
