name: release hotfix
on:
  push:
    branches:
      - v[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

jobs:
  init-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          version_format: "v${major}.${minor}"
          bump_each_commit: true
          version_from_branch: "/v([0-9]+.[0-9]+$|[0-9]+)$/"
      - name: tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
