name: release hotfix
on:
  push:
    branches:
      - v[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

jobs:
  init-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: ${{github.ref_name}}.
          prefix: ${{github.ref_name}}
      - name: Create next version
        env:
          VERSION: ${{ steps.previoustag.outputs.tag }}
        run: |
          previous_i=${VERSION#*.}
          if [ -z "$previous_i" ]; then
            next_i=0
          else
            next_i=$((previous_i + 1))
          fi
          git tag "${{github.ref_name}}.$next_i"
          git push origin "${{github.ref_name}}.$next_i"
