name: Version release
on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      version:
        description: "Version name"
        type: string
        required: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version || github.ref_name }}

      - name: Generate release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          previous_latest=$(gh release list --jq '.[] | select(.isLatest == true)' --json name,isLatest | jq -r '.name')
          gh release create --draft --generate-notes --notes-start-tag $previous_latest ${{ github.ref_name }}
  deploy-default:
    needs: release
    uses: ./.github/workflows/s3-mlstg-deploy.yml
    with:
      version: ${{ inputs.version || github.ref_name }}
  deploy-qlover:
    needs: release
    uses: ./.github/workflows/s3-mlstg-qlover-deploy.yml
    with:
      version: ${{ inputs.version || github.ref_name }}
  deploy-channel:
    needs: release
    uses: ./.github/workflows/s3-mlstg-channel-deploy.yml
    with:
      version: ${{ inputs.version || github.ref_name }}
