name: release hotfix
on:
  push:
    branches:
      - v[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

jobs:
  tag-version:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: paulhatch/semantic-version@latest
        with:
          version_from_branch: "/v([0-9]+.[0-9]+$|[0-9]+)$/"
