name: release branch
on:
  push:
    branches:
      - release-20[0-9][0-9][0-1][0-9][0-3][0-9]

jobs:
  create-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get this version
        run: echo "THIS_VERSION=${GITHUB_REF_NAME#"release-"}" >> $GITHUB_ENV
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: ${{ env.THIS_VERSION }}.
          prefix: ${{env.THIS_VERSION}}
      - name: Create next version
        id: createversion
        env:
          VERSION: ${{ steps.previoustag.outputs.tag }}
          GH_TOKEN: ${{ github.token }}
        run: |
          previous_i=${VERSION#*.}
          if [ -z "$previous_i" ]; then
            next_i=0
            compare_target=$(gh release list --jq '.[] | select(.isLatest == true)' --json name,isLatest | jq -r '.name')
          else
            next_i=$((previous_i + 1))
            compare_target=$VERSION
          fi
          git tag "$THIS_VERSION.$next_i"
          git push origin "$THIS_VERSION.$next_i"
          gh release create --prerelease --generate-notes --notes-start-tag $compare_target "$THIS_VERSION.$next_i"
