name: Tag version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        type: string
        required: true

jobs:
  tag-version:
    name: Tag version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
  tag-release:
    needs: tag-version
    permissions: write-all
    uses: ./.github/workflows/release-version.yml
    with:
      version: ${{ github.event.inputs.version }}
